import streamlit as st
import pandas as pd
import subprocess
import os
from datetime import datetime

# Page Configuration
st.set-page_config(page_title="NIST 800-171 Auditor", page_icon="🛡️", layout="wide")

st.title("🛡️ NIST 800-171 Automated Compliance Dashboard")
st.markdown("---")

# Sidebar for Controls
st.sidebar.header("Audit Actions")
if st.sidebar.button("🚀 Run System Audit"):
    with st.spinner("Executing NIST scans... (Requires Admin elevation)"):
        # This triggers your existing scanner.py logic
        subprocess.run(["python", "scanner.py"], shell=True)
        st.sidebar.success("Audit Finished!")

# Main Dashboard Logic
report_path = "reports/audit_results.csv"

if os.path.exists(report_path):
    # Load the data generated by your scanner
    df = pd.read_csv(report_path)
    
    # --- Top Row Metrics ---
    total_checks = len(df)
    compliant_count = len(df[df['status'] == 'Compliant'])
    non_compliant_count = total_checks - compliant_count
    
    col1, col2, col3 = st.columns(3)
    col1.metric("Total Controls", total_checks)
    col2.metric("Compliant", compliant_count, delta="Pass", delta_color="normal")
    col3.metric("Non-Compliant", non_compliant_count, delta="-Fail", delta_color="inverse")

    st.markdown("---")

    # --- Middle Row: Visualization ---
    left_col, right_col = st.columns([1, 2])
    
    with left_col:
        st.subheader("Compliance Ratio")
        # Creating a simple pie-style summary
        status_counts = df['status'].value_counts()
        st.bar_chart(status_counts)

    with right_col:
        st.subheader("Detailed Control Findings")
        # Color coding the table
        def color_status(val):
            color = 'green' if val == 'Compliant' else 'red'
            return f'color: {color}; font-weight: bold'
        
        st.dataframe(df.style.applymap(color_status, subset=['status']), use_container_width=True)

    # --- Bottom Row: JSON Raw Data ---
    with st.expander("View Raw JSON Report"):
        if os.path.exists("reports/audit_results.json"):
            with open("reports/audit_results.json", "r") as f:
                st.json(f.read())
else:
    st.info("👋 No audit data found. Click 'Run System Audit' in the sidebar to begin.")
